config/routes.rb
Rails.application.routes.draw do
  resources :prescriptions

  resources :patients

  root 'patients#index'

end

app/models/patient.rb
class Patient < ActiveRecord::Base
	has_many :prescriptions
end

app/models/prescription.rb
class Prescription < ActiveRecord::Base
  belongs_to :patient
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]

  # GET /patients
  # GET /patients.json
  def index
    @patients = Patient.all

    respond_to do |format|
       format.json 

    end
  end

  # GET /patients/1
  # GET /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to @patient, notice: 'Patient was successfully created.' }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1
  # PATCH/PUT /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to @patient, notice: 'Patient was successfully updated.' }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient.destroy
    respond_to do |format|
      format.html { redirect_to patients_url, notice: 'Patient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def patient_params
      params.require(:patient).permit(:firstName, :lastName, :age)
    end
end

app/controllers/prescriptions_controller.rb
class PrescriptionsController < ApplicationController
  before_action :set_prescription, only: [:show, :edit, :update, :destroy]

  # GET /prescriptions
  # GET /prescriptions.json
  def index
    @prescriptions = Prescription.all
  end

  # GET /prescriptions/1
  # GET /prescriptions/1.json
  def show
  end

  # GET /prescriptions/new
  def new
    @prescription = Prescription.new
  end

  # GET /prescriptions/1/edit
  def edit
  end

  # POST /prescriptions
  # POST /prescriptions.json
  def create
    @prescription = Prescription.new(prescription_params)

    respond_to do |format|
      if @prescription.save
        format.html { redirect_to @prescription, notice: 'Prescription was successfully created.' }
        format.json { render :show, status: :created, location: @prescription }
      else
        format.html { render :new }
        format.json { render json: @prescription.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /prescriptions/1
  # PATCH/PUT /prescriptions/1.json
  def update
    respond_to do |format|
      if @prescription.update(prescription_params)
        format.html { redirect_to @prescription, notice: 'Prescription was successfully updated.' }
        format.json { render :show, status: :ok, location: @prescription }
      else
        format.html { render :edit }
        format.json { render json: @prescription.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prescriptions/1
  # DELETE /prescriptions/1.json
  def destroy
    @prescription.destroy
    respond_to do |format|
      format.html { redirect_to prescriptions_url, notice: 'Prescription was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prescription
      @prescription = Prescription.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def prescription_params
      params.require(:prescription).permit(:name, :instructions, :patient_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/prescriptions_helper.rb
module PrescriptionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sync</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/patients/_form.html.erb
<%= form_for(@patient) do |f| %>
  <% if @patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
      <% @patient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :firstName %><br>
    <%= f.text_field :firstName %>
  </div>
  <div class="field">
    <%= f.label :lastName %><br>
    <%= f.text_field :lastName %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.text_field :age %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/patients/edit.html.erb
<h1>Editing patient</h1>

<%= render 'form' %>

<%= link_to 'Show', @patient %> |
<%= link_to 'Back', patients_path %>

app/views/patients/index.html.erb
<h1>Listing patients</h1>

<table>
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Age</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @patients.each do |patient| %>
      <tr>
        <td><%= patient.firstName %></td>
        <td><%= patient.lastName %></td>
        <td><%= patient.age %></td>
        <td><%= link_to 'Show', patient %></td>
        <td><%= link_to 'Edit', edit_patient_path(patient) %></td>
        <td><%= link_to 'Destroy', patient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Patient', new_patient_path %>

app/views/patients/new.html.erb
<h1>New patient</h1>

<%= render 'form' %>

<%= link_to 'Back', patients_path %>

app/views/patients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @patient.firstName %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @patient.lastName %>
</p>

<p>
  <strong>Age:</strong>
  <%= @patient.age %>
</p>

<%= link_to 'Edit', edit_patient_path(@patient) %> |
<%= link_to 'Back', patients_path %>

app/views/prescriptions/_form.html.erb
<%= form_for(@prescription) do |f| %>
  <% if @prescription.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@prescription.errors.count, "error") %> prohibited this prescription from being saved:</h2>

      <ul>
      <% @prescription.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :instructions %><br>
    <%= f.text_field :instructions %>
  </div>
  <div class="field">
    <%= f.label :patient_id %><br>
    <%= f.text_field :patient_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/prescriptions/edit.html.erb
<h1>Editing prescription</h1>

<%= render 'form' %>

<%= link_to 'Show', @prescription %> |
<%= link_to 'Back', prescriptions_path %>

app/views/prescriptions/index.html.erb
<h1>Listing prescriptions</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Instructions</th>
      <th>Patient</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @prescriptions.each do |prescription| %>
      <tr>
        <td><%= prescription.name %></td>
        <td><%= prescription.instructions %></td>
        <td><%= prescription.patient %></td>
        <td><%= link_to 'Show', prescription %></td>
        <td><%= link_to 'Edit', edit_prescription_path(prescription) %></td>
        <td><%= link_to 'Destroy', prescription, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Prescription', new_prescription_path %>

app/views/prescriptions/new.html.erb
<h1>New prescription</h1>

<%= render 'form' %>

<%= link_to 'Back', prescriptions_path %>

app/views/prescriptions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @prescription.name %>
</p>

<p>
  <strong>Instructions:</strong>
  <%= @prescription.instructions %>
</p>

<p>
  <strong>Patient:</strong>
  <%= @prescription.patient %>
</p>

<%= link_to 'Edit', edit_prescription_path(@prescription) %> |
<%= link_to 'Back', prescriptions_path %>